<?php 

/**
 * Implementation of hook_theme
 */
function wistar_timeline_theme() {
	return array(
		'wistar_timeline' => array(
			'type' => 'theme',
			'template' => 'wistar-timeline'
		)
	);
}

/**
 * implementation of hook_menu
 */	
function wistar_timeline_menu() {
	$items = array();
	
	$items['the-institute/our-history/timeline'] = array(
		'title' => 'Timeline',
		'page callback' => 'theme',
		'page arguments' => array('wistar_timeline'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);
	
	return $items;
}


