<?php

/**
 * implementation of hook_menu
 */
function wistar_theme_menu() {
	$items = array();

	$tech_terms = taxonomy_get_tree(5);
	foreach($tech_terms as $idx => $term) {
		$term_arg = strtolower(preg_replace('/[^A-Za-z0-9]/', '-', $term->name));
		$items['technology-transfer/technologies/' . $term_arg] = array(
			'title' => $term->name,
			'type' => MENU_NORMAL_ITEM,
			'page callback' => 'wistar_theme_technology_view_ultra_preprocess',
			'page arguments' => array('page_1', 2),
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
			'menu_name' => 'primary-links',
		);
	}

	$tools_terms = taxonomy_get_tree(9);
	foreach($tools_terms as $idx => $term) {
		$term_arg = strtolower(preg_replace('/[^A-Za-z0-9]/', '-', $term->name));
		$items['technology-transfer/research-tools/' . $term_arg] = array(
			'title' => $term->name,
			'type' => MENU_NORMAL_ITEM,
			'page callback' => 'wistar_theme_technology_view_ultra_preprocess',
			'page arguments' => array('page_2', 2),
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
			'menu_name' => 'primary-links',
		);
	}

	$inventors = wistar_theme_get_inventor_list();
	foreach($inventors as $idx => $node) {
		$items['technology-transfer/by-inventor/' . $node->nid] = array(
			'title' => $node->title,
			'type' => MENU_NORMAL_ITEM,
			'page callback' => 'wistar_theme_technology_view_ultra_preprocess',
			'page arguments' => array('page_3', 2),
			'access callback' => 'user_access',
			'access arguments' => array('access content'),
			'menu_name' => 'primary-links',
		);
	}

	return $items;
}

/**
 * Implementation of hook_theme
 */
function wistar_theme_theme() {

	return array(
		'wistar_home_masthead_carousel' => array(
			'type' => 'theme',
			'template' => 'wistar-home-masthead-carousel',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_page_footer' => array(
			'type' => 'theme',
			'template' => 'wistar-page-footer',
			'arguments' => array(
				'messages' => null,
				'closure' => null,
				'quicklinks' => true,
				'alert' => null
			)
		),
		'wistar_page_head' => array(
			'type' => 'theme',
			'template' => 'wistar-page-head',
			'arguments' => array(
				'head_title' => null,
				'head' => null,
				'meta' => null,
				'scripts' => null,
				'styles' => null,
				'body_classes' => null
			)
		),
		'wistar_landing_page_masthead_carousel' => array(
			'type' => 'theme',
			'template' => 'wistar-landing-page-masthead-carousel',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_messages' => array(
			'type' => 'theme',
			'template' => 'wistar-messages',
			'arguments' => array(
				'messages' => null
			)
		),
		'wistar_logo' => array(
			'type' => 'theme',
			'template' => 'wistar-logo',
		),
		'wistar_nav' => array(
			'type' => 'theme',
			'template' => 'wistar-nav',
			'arguments' => array(
				'secondary_links' => menu_secondary_links()
			)
		),
		'wistar_scientists_menu' => array(
			'type' => 'theme',
			'template' => 'wistar-scientists-menu',
			'arguments' => array(
				'scientists' => wistar_theme_load_scientists()
			)
		),
		'wistar_tools' => array(
			'type' => 'theme',
			'template' => 'wistar-tools',
		),
		'wistar_ga' => array(
			'type' => 'theme',
			'template' => 'wistar-ga',
		),
		'wistar_sign_up_form' => array(
			'type' => 'theme',
			'template' => 'wistar-sign-up-form',
		),
		'wistar_social_tabs' => array(
			'type' => 'theme',
			'template' => 'wistar-social-tabs',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_callout' => array(
			'type' => 'theme',
			'template' => 'wistar-callout',
			'arguments' => array(
				'node' => null,
				'idx' => null,
				'options' => array()
			)
		),
		'wistar_callout_home' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-home',
			'arguments' => array(
				'title' => '',
				'image' => '',
				'text' => '',
				'attributes' => array()
			)
		),
		'wistar_callout_home_video' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-home-video',
			'arguments' => array(
				'node' => null,
				'idx' => 0
			)
		),
		'wistar_callout_header_single' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-header-single',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_callout_header_newsletter' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-header-newsletter',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_callout_header_four_up' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-header-four-up',
			'arguments' => array(
				'node' => null,
				'main_text' => null,
				'body_text' => null,
				'active' => null
			)
		),
		'wistar_callout_landing_page_callout_img' => array(
			'type' => 'theme',
			'template' => 'wistar-callout-landing-page-callout-img',
			'arguments' => array(
				'node' => null,
				'callout_images' => null,
				'callout_links' => null,
				'wysiwyg_content' => null,
			),
		),
		'wistar_read_more' => array(
			'type' => 'theme',
			'arguments' => array(
				'text' => 'Read More',
				'path' => '/'
			)
		),
		'wistar_vertical_tabs' => array(
			'type' => 'theme',
			'template' => 'wistar-vertical-tabs',
			'arguments' => array(
				'bid' => null,
				'use_accordion' => false
			)
		),
		'wistar_vertical_tabs_custom' => array(
			'type' => 'theme',
			'template' => 'wistar-vertical-tabs-custom',
			'arguments' => array(
				'content' => null
			)
		),
		'wistar_content_heading' => array(
			'type' => 'theme',
			'template' => 'wistar-content-heading',
			'arguments' => array(
				'node' => null,
				'custom_title' => null
			)
		),
		'wistar_page_navigation' => array(
			'type' => 'theme',
			'template' => 'wistar-page-navigation',
			'arguments' => array(
				'node' => null,
				'custom_title' => null
			)
		),
		'wistar_quicklinks' => array(
			'type' => 'theme',
			'template' => 'wistar-quicklinks'
		),
		'wistar_alert' => array(
			'type' => 'theme',
			'template' => 'wistar-alert',
			'arguments' => array(
				'alert' => null
			)
		),
		'wistar_featured_image' => array(
			'type' => 'theme',
			'template' => 'wistar-featured-image',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_microsite_sidebar_quicklinks' => array(
			'type' => 'theme',
			'template' => 'wistar-microsite-sidebar-quicklinks',
			'arguments' => array(
				'quicklinks' => null
			)
		),
		'wistar_microsite_menu' => array(
			'type' => 'theme',
			'template' => 'wistar-microsite-menu',
			'arguments' => array(
				'parent' => null
			)
		),
		'wistar_content_links' => array(
			'type' => 'theme',
			'template' => 'wistar-content-links',
			'arguments' => array(
				'node' => null
			)
		),
		'wistar_content_callouts' => array(
			'type' => 'theme',
			'template' => 'wistar-content-callouts',
			'arguments' => array(
				'node' => null,
				'subheading' => null
			)
		),
		'wistar_share' => array(
			'type' => 'theme',
			'template' => 'wistar-share',
			'arguments' => array(
				'nid' => null,
				'title' => null
			)
		),
		'wistar_gallery' => array(
			'type' => 'theme',
			'template' => 'wistar-gallery',
			'arguments' => array(
				'images' => null,
				'thumb_preset' => null,
				'thumbs_per_row' => null,
				'notice' => null
			)
		)
	);
}

/**
 * formats a read more link
 */
function theme_wistar_read_more($text, $path) {
	if(!$text) $text = 'Read More';
	return '<a class="more" href="' . $path . '">' . $text . ' <span class="more_arrow">&gt;</span></a>';
}

/**
 * implementation of pagination for blog posts
 */
function wistar_theme_nodeapi(&$node, $op) {
	switch($op) {
		case 'load':
			if($node->type == 'post') {
				$result = db_query('SELECT nid FROM {content_type_post} ORDER BY field_post_date_value DESC');
				$node->prev = null;
				$node->next = null;

				while($row = db_fetch_object($result)) {
					if($row->nid == $node->nid) {
						$next_row = db_fetch_object($result);
						$node->next = $next_row->nid;
						break;
					}

					$node->prev = $row->nid;
				}
			}

			break;
		case 'view':
			break;
		default;
			break;
	}
}

/**
 * retreives a list of scientists for output in the menu
 */
function wistar_theme_load_scientists() {
	static $scientists;
	if(!$scientists || !count($scientists)) {
		$view = views_get_view('scientist_menu');
		$view->set_display('default');
		$view->pre_execute();
		$view->execute();
		$scientists = $view->result;
	}

	return $scientists;
}

/**
 * gets the active item
 */
function wistar_theme_get_active($type) {
	$nid = db_result(db_query('SELECT nid FROM {node} WHERE type = "%s" ORDER BY nid DESC LIMIT 1', $type));

	if( $nid && is_numeric($nid) ) {
		return node_load($nid, null, null);
	}

	return false;
}

/**
 * returns the progress bar for donation form
 */
function wistar_theme_donation_progress_bar($index = 0, $steps = array('Address & Donation', 'Thank You')) {
	$ret = '<div class="form-progress">';
	foreach($steps as $idx => $step) {
		$idx_label = $idx + 1;
		$class = 'page page-' . $idx_label;
		if( $idx == $index ) $class .= ' active';
		if( $idx == count($steps) - 1 ) $class .= ' last';
		$ret .= "\n" . '<div class="' . $class . '">' . $step . '</div>';
	}

	$ret .= "\n" . '</div>';
	return $ret;
}

/**
 * Search form block alter
 */
function wistar_theme_form_search_block_form_alter(&$form, &$form_state) {
	unset($form['search_block_form']['#title']);
}

/**
 * comment form alter
 */
function wistar_theme_form_comment_form_alter(&$form, &$form_state) {
	global $user;

	if($user->uid == 0) {
		$form['name']['#default_value'] = '';
	}

	$form['_author']['#value'] = '';

	if(isset($form['mail'])) {
		unset($form['mail']);
	}

	if(isset($form['homepage'])) {
		unset($form['homepage']);
	}
}

/* Search form alter */
function wistar_theme_form_search_form_alter(&$form, &$form_state) {
	$form['basic']['inline']['keys']['#default_value'] = arg(2);
}

/**
 * Helper fucntion for getting terms in the proper format for theme list_items
 */
function wistar_theme_get_term_list($terms, $path_prefix) {
	$ret = array();
	foreach($terms as $idx => $term) {
		$ret[] = array('data' => l($term->name, $path_prefix . strtolower(str_replace(' ', '-', $term->name))));
	}

	return $ret;
}

/**
 * Helper fucntion for getting terms in the proper format for theme list_items
 */
function wistar_theme_get_inventor_list() {
	$ret = array();

	$result = db_query('SELECT * FROM content_field_technology_inventor_ref where field_technology_inventor_ref_nid > 0 GROUP BY field_technology_inventor_ref_nid');
	while($row = db_fetch_object($result)) {
		$node = node_load($row->field_technology_inventor_ref_nid);
		$ret[] = $node;
	}

	return $ret;
}

/**
 * helper function to get the latest backrground image
 */
function wistar_theme_site_bg() {
	$nid = db_result(db_query('SELECT nid from {node} WHERE type = "site_bg" AND status > 0 ORDER BY created DESC LIMIT 1'));
	if( is_numeric($nid) && $nid ) {
		$node = node_load($nid);
		return '/' . $node->field_bg_image[0]['filepath'];
	}

	return null;
}

/**
 * load up the alert for the page
 */
function wistar_theme_get_alert() {
	$nid = db_result(db_query('SELECT * FROM {node} WHERE type = "alert" AND status > 0 ORDER BY nid DESC LIMIT 1'));
	if( $nid && is_numeric($nid) ) {
		$alert = node_load($nid);
		if((int)$alert->field_active[0]['value'] == 1) {
			return $alert;
		}
	}

	return null;
}


/**
 * implementation of views_pre_render
 */
function wistar_theme_views_pre_render(&$view) {
	global $authoritative_breadcrumbs;
	$authoritative_breadcrumbs = true;

	if ( $view->name == 'blog' && preg_match('/^page_(1|2)/', $view->current_display) ) {
		$crumb[] = l('Home', '<front>');
		$crumb[] = l('Wistar Today', 'wistar-today');
		$crumb[] = l('Wistar Wire', 'wistar-today/wistar-wire');

		if ( isset($view->args[0]) && $view->args[0] != $view->name && ($arg1 = $view->args[0]) ) {
			$arg1 = ucwords(str_replace('-', ' ', $arg1));
			$crumb[] = $view->args[0];
			drupal_set_title('Wistar Wire: ' . $arg1);
		}

		drupal_set_breadcrumb($crumb);
	}

	if( $view->name == 'press' && $view->current_display == 'page_1') {
		$path = $view->display[$view->current_display]->display_options['path'];
		menu_set_active_item($path);


		if(count($view->args) > 0) {
			$crumbs = drupal_get_breadcrumb();
			array_pop($crumbs);
			$crumbs[] = $view->args[0];
			drupal_set_breadcrumb($crumbs);
		}
		else {
			$crumbs = drupal_get_breadcrumb();
			$crumbs[] = $view->display[$view->current_display]->display_title;
			drupal_set_breadcrumb($crumbs);
		}
	}

	if( $view->name == 'technology') {

		if(count($view->args) > 0) {
			$crumbs = drupal_get_breadcrumb();
			array_pop($crumbs);
			$crumbs[] = ucwords(str_replace('-', ' ', $view->args[0]));;

			drupal_set_breadcrumb($crumbs);
		}
		else {
			$crumbs = drupal_get_breadcrumb();
			$crumbs[] = $view->display[$view->current_display]->display_title;
			drupal_set_breadcrumb($crumbs);
		}
	}

	if( $view->name == 'events' && preg_match('/^page_/', $view->current_display)) {
		$crumbs = drupal_get_breadcrumb();
		$crumbs[] = l($view->display[$view->current_display]->display_title, $_GET['q']);
		drupal_set_breadcrumb($crumbs);
	}

	if ( $view->name == 'article' && preg_match('/^page_(1|2)/', $view->current_display) ) {
		$crumb[] = l('Home', '<front>');
		$crumb[] = l('Wistar Today', 'wistar-today');
		$crumb[] = l('News and Media', 'node/262');
		$crumb[] = l('Focus Newsletter', 'news-and-media/focus-newsletter');

		if ( isset($view->args[0]) && $view->args[0] != $view->name && ($arg1 = $view->args[0]) ) {
			$arg1 = ucwords(str_replace('-', ' ', $arg1));
			$crumb[] = $view->args[0];
			drupal_set_title('Articles: ' . $arg1);
		}

		drupal_set_breadcrumb($crumb);
	}

}

/**
 * implementation of custom views handler
 */
function wistar_theme_technology_view_ultra_preprocess($display_id, $arg) {
  if ($view = views_get_view('technology')) {
    return $view->execute_display($display_id, array($arg));
  }
}

/* Note form alter */
function wistar_theme_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'article_node_form') {
		$form['#after_build'][] = 'wistar_theme_article_node_form_after_build';
	}
	if ($form_id == 'user_profile_form') {
	}
	if ($form_id == 'post_node_form') {
		$form['#after_build'][] = 'wistar_theme_post_image_widget';
	}
	if ($form_id == 'press_node_form') {
		$form['#after_build'][] = 'wistar_theme_post_image_widget';
	}
	if (strpos($form_id,'node_form') !== false) {
		$date = date_now();
		$create_date = date_format_date($date,'custom', 'Y-m-d H:i:s O');
		$form['author']['date']['#attributes'] = array('autocomplete'=>'off');
		
		if (!isset($form['author']['date']['#default_value'])) {
			$form['author']['date']['#default_value'] = $create_date;
		}
		
		if (!isset($form['title']['#default_value'])) {
			$form['title']['#default_value'] = ' ';
		}
		$form['#attributes'] = array('autocomplete'=>'off');
		
	}
}

function wistar_theme_article_node_form_after_build(&$form, &$form_state) {
	if (!empty($form['field_article_scientist']['nid']['nid']['#options'])) {
		$options = &$form['field_article_scientist']['nid']['nid']['#options'];
		$nids = wistar_theme_taxonomy_select_article_scientists(array(40), $operator = 'or', $depth = 'all', $pager = FALSE);
		if(!empty($nids) && !empty($options)) {
			foreach($options as $nid=>$title) {
				if(!isset($nids[$nid])) {
					unset($options[$nid]);
				}
			}
		}
	}
	return $form;
}

function wistar_theme_taxonomy_select_article_scientists($tids = array(), $operator = 'or', $depth = 0, $pager = TRUE, $order = 'n.sticky DESC, n.created DESC') {
	$nids = array();

	 // For each term ID, generate an array of descendant term IDs to the right depth.
    $descendant_tids = array();
    if ($depth === 'all') {
      $depth = NULL;
    }
	foreach ($tids as $index => $tid) {
		$term = taxonomy_get_term($tid);
		$tree = taxonomy_get_tree($term->vid, $tid, -1, $depth);
		$descendant_tids[] = array_merge(array($tid), array_map('_taxonomy_get_tid_from_term', $tree));
	}
	$args = call_user_func_array('array_merge', $descendant_tids);
  	$placeholders = db_placeholders($args, 'int');
	$sql = 'SELECT DISTINCT(n.nid), n.sticky, n.title, n.created FROM {node} n INNER JOIN {term_node} tn ON n.vid = tn.vid WHERE tn.tid IN ('. $placeholders .') AND n.status = 1 AND n.type="scientist" ORDER BY '. $order;
	$result = db_query($sql, $args);
	while ($node = db_fetch_object($result)) {
		$nids[$node->nid] = $node->nid;
	}
	return $nids;
}

function wistar_theme_init() {
	global $user;
	// user already entered the password?
	if (isset($_SESSION['_protected_node']['passwords'][1963])) {
		$when = $_SESSION['_protected_node']['passwords'][1963];
		$expire = 30*60; //30 mins
		if( ($when + $expire) <= time() ) {
			unset($_SESSION['_protected_node']['passwords'][1963]);
		}
	}
}
function wistar_theme_post_image_widget($form, &$form_state) {
	if(isset($form['field_post_image'])){
		foreach ($form['field_post_image'] as $index => $image_widget) {
			if(is_array($image_widget) && $image_widget['#title'] == 'Image' && $image_widget['#type'] == 'imagefield_widget'){
				//pa($image_widget['data']['alt']['#title'],1);
				$form['field_post_image'][$index]['data']['alt']['#title'] = 'Caption';
				$form['field_post_image'][$index]['data']['alt']['#description'] = '';
			}
		}
	}
    return $form;
}

function wistar_theme_form_splash_admin_what_alter($form, &$form_state){
	wysiwyg_extra_build_wysiwyg($form['splash_what'], 'content');
          $form['splash_what']['content']['content']['#rows'] = 18;
}